// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6hvNdz0-oLGGGEgxjUX5J76q2SowAtyo',
    appId: '1:698120275482:web:a29566621a7eb908a8f3a3',
    messagingSenderId: '698120275482',
    projectId: 'chat-app-61325',
    authDomain: 'chat-app-61325.firebaseapp.com',
    storageBucket: 'chat-app-61325.firebasestorage.app',
    measurementId: 'G-K91HLGCGZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz8GnMrfDuduUPfjRo0rPE98eHNPGxNXM',
    appId: '1:698120275482:android:f908f60d37fa9668a8f3a3',
    messagingSenderId: '698120275482',
    projectId: 'chat-app-61325',
    storageBucket: 'chat-app-61325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDh0JnAvTUr04I8YhFwGWSKkHdpCV_gV0',
    appId: '1:698120275482:ios:79d50a9c2ba7e94ba8f3a3',
    messagingSenderId: '698120275482',
    projectId: 'chat-app-61325',
    storageBucket: 'chat-app-61325.firebasestorage.app',
    iosBundleId: 'com.example.chatAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDh0JnAvTUr04I8YhFwGWSKkHdpCV_gV0',
    appId: '1:698120275482:ios:79d50a9c2ba7e94ba8f3a3',
    messagingSenderId: '698120275482',
    projectId: 'chat-app-61325',
    storageBucket: 'chat-app-61325.firebasestorage.app',
    iosBundleId: 'com.example.chatAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6hvNdz0-oLGGGEgxjUX5J76q2SowAtyo',
    appId: '1:698120275482:web:6c5bdb5c30df92e1a8f3a3',
    messagingSenderId: '698120275482',
    projectId: 'chat-app-61325',
    authDomain: 'chat-app-61325.firebaseapp.com',
    storageBucket: 'chat-app-61325.firebasestorage.app',
    measurementId: 'G-BQLXPGY267',
  );
}
